In [34]:
import numpy as np

class Sudoku(object): 
    '''
    #
    int mat[]; 
    int N; // number of columns/rows. 
    int SRN; // square root of N 
    int K; // No. Of missing digits
    '''
    #Constructor 
    #Sudoku(int N, int K) 
    def __init__(self,N,K):
        self.N = N 
        self.K = K 
        self.sol = []

        # Compute square root of N 
        SRNd = np.sqrt(self.N) 
        self.SRN = int(SRNd)
        #print(self.SRN)

        self.mat = np.array([[0]*N]*N)
        
    def fillValues(self) :
        # Fill the diagonal of SRN x SRN matrices 
        self.fillDiagonal() 
        #print(self.mat)
        # Fill remaining blocks 
        self.fillRemaining(0, self.SRN) 
        print(self.mat)
        self.sol = self.mat
        # Remove Randomly K digits to make game 
        self.removeKDigits()
        return self.mat
        
    # Fill the diagonal SRN number of SRN x SRN matrices 
    def fillDiagonal(self):
        for i in range(0, self.N, self.SRN):       #(int i = 0; i<N; i=i+SRN) 
            # for diagonal box, start coordinates->i==j 
            self.fillBox(i, i) 

    # Returns false if given 3 x 3 block contains num. 
    def unUsedInBox(self, rowStart, colStart, num):
        for i in range(self.SRN):         #(int i = 0; i<SRN; i++) 
            for j in range(self.SRN):      #(int j = 0; j<SRN; j++) 
                if (self.mat[rowStart+i][colStart+j]==num): 
                    return False
        return True

    # Fill a 3 x 3 matrix. 
    def fillBox(self, row, col):
        num=0
        #N = self.N
        for i in range(self.SRN):      #(int i=0; i<SRN; i++)         
            for j in range(self.SRN):  #(int j=0; j<SRN; j++) 
                while not(self.unUsedInBox(row, col, num)):
                    num = self.randomGenerator(self.N); 
                self.mat[row+i][col+j] = num; 

                
    # Random generator 
    def randomGenerator(self, num):
        return np.floor((np.random.random()*num)+1); 

    # Check if safe to put in cell 
    def CheckIfSafe(self, i, j, num): 
        return (self.unUsedInRow(i, num) and 
                self.unUsedInCol(j, num) and 
                self.unUsedInBox(i-i%self.SRN, j-j%self.SRN, num)); 


    # check in the row for existence 
    def unUsedInRow(self, i, num): 
        for j in range(self.N):        #(int j = 0; j<N; j++) 
          if (self.mat[i][j] == num): 
                return False;
        return True 

    # check in the row for existence 
    def unUsedInCol(self, j, num): 
        for i in range(self.N):       #(int i = 0; i<N; i++) 
            if (self.mat[i][j] == num): 
                return False 
        return True

    # A recursive function to fill remaining 
    # matrix 
    def fillRemaining(self, i, j) :
        N = self.N
        # System.out.println(i+" "+j); 
        if (j>=N and i<N-1): 
            i = i + 1
            j = 0

        if (i>=N and j>=N): 
            return true; 

        if (i < self.SRN): 
        
            if (j < self.SRN): 
                j = self.SRN
        
        elif (i < N - self.SRN) :
        
            if (j==(int)(i/self.SRN)*self.SRN) :
                j = j + self.SRN
        
        elif (j == N - self.SRN): 
                i = i + 1 
                j = 0 
                if (i>=N): 
                    return True

        for num in range(1,N+1):     #(int num = 1; num<=N; num++) 
            if (self.CheckIfSafe(i, j, num)):          
                self.mat[i][j] = num 
                if (self.fillRemaining(i, j+1)): 
                    return True
                self.mat[i][j] = 0     
        return False


    # Remove the K no. of digits to 
    # complete game 
    def removeKDigits(self):
        count = self.K
        N = self.N
        while (count != 0): 
            cellId = self.randomGenerator(N*N) 
            # extract coordinates i and j 
            i = int(cellId/N)-1; 
            j = int(cellId%9); 
            #print(cellId, i, j); 
            if (j != 0): 
                j = j - 1; 
            if (self.mat[i][j] != 0):             
                count-=1
                self.mat[i][j] = 0

    # Print sudoku 
    def printSudoku(self):
        N = self.N
        for i in range(N) :     #(int i = 0; i<N; i++)          
            for j in range(N):     #(int j = 0; j<N; j++) 
                print(self.mat[i][j],"\t") 
            print(); 
         
        print(); 
     

# Driver code 
def main():
    N = 9; K = 50; 
    sudoku = Sudoku(N, K) 
    grid = sudoku.fillValues()
    print(grid)
    #sudoku.printSudoku()
    #print(sudoku.sol)

main()

[[5 6 9 1 7 2 3 4 8]
 [1 2 4 3 8 5 7 9 6]
 [8 3 7 4 6 9 2 5 1]
 [3 5 8 6 2 7 9 1 4]
 [2 9 1 5 3 4 8 6 7]
 [7 4 6 9 1 8 5 3 2]
 [4 8 3 2 5 6 1 7 9]
 [6 7 5 8 9 1 4 2 3]
 [9 1 2 7 4 3 6 8 5]]
[[0 0 9 0 0 2 0 0 8]
 [0 0 4 0 0 0 7 0 6]
 [0 0 0 0 6 0 0 0 1]
 [3 0 8 0 0 0 9 0 4]
 [0 9 1 5 3 4 0 6 7]
 [0 0 0 0 1 8 0 0 2]
 [0 0 0 2 0 0 0 7 9]
 [0 0 0 8 0 0 0 0 3]
 [0 1 2 0 0 0 6 0 5]]


In [31]:
N, K = 9, 3
#mat = np.array([[0]*N]*N)
grid = Sudoku(N, K)

In [23]:
grid

In [24]:
grid.mat

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
grid.SRN

3

In [26]:
np.random.random()

0.21441059014955244

In [27]:
grid.mat[0][0] !=0

False

In [35]:
grid.sol

[]